version: '3.3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ddm
      # MYSQL_USER: root
      # MYSQL_PASSWORD: root
    ports:
      - 13306:3306
    volumes:
      - myvolume:/var/lib/mysql
  app:
    build: .
    volumes:
      - ./src:/app
    ports:
      - 80:80
    depends_on:
      - db

volumes:
  myvolume:
